-
  name: 'Installing zabbix server'
  hosts: servers
  become: yes
  tasks:
    - name: 'Checking if zabbix_server installed or no'
      package_facts:
        manager: 'auto'

    - name: Ensure a list of packages  installed on Zabbix-server
      yum:
        name: "{{ item }}"
        state: latest
      loop:
          - https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
          - httpd
          - epel-release
          - php
          - php-common
          - php-mcrypt
          - php-cli
          - php-gd
          - php-curl
          - php-mysql
          - mariadb-server
          - MySQL-python
          - zabbix-get
          - zabbix-agent
          - zabbix-server-mysql
          - zabbix-web-mysql

    - name: Ensure a list of services  started on Zabbix-server
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - mariadb
        - firewalld
    - name: Ensure a list of systemctl services  started on Zabbix-server
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - zabbix-agent
        - zabbix-server

    - name: modify /etc/php.ini
      replace:
        path: /etc/httpd/conf.d/zabbix.conf
        regexp: '{{  item.editable  }}'
        replace: '{{  item.edited  }}'
      loop:
        - { editable: 'php_value max_execution_time 300', edited: 'php_value max_execution_time 600' }
        - { editable: 'max_input_time = 60', edited: 'max_input_time = 700' }
        - { editable: 'php_value memory_limit 128M', edited: 'php_value memory_limit 256M' }
        - { editable: 'post_max_size = 16M', edited: 'post_max_size = 32M' }
        - { editable: 'upload_max_filesize = 2M', edited: 'upload_max_filesize = 16M' }
        - { editable: '# php_value date.timezone Europe/Riga', edited: 'php_value date.timezone Asia/Yerevan' }
      notify: "restart httpd"


    - name: Configure firewall to allow services on DB
      firewalld:
        port: "{{  item  }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - "10051/tcp"
        - "10050/tcp"
        - "80/tcp"
      notify: "restart firewalld"

    - name: Create dadabase zabbix;
      mysql_db:
          collation: utf8_bin
          encoding: 'utf8'
          name: zabbix
          state: present

    - name: Create database user with name 'zabbix-user'
      mysql_user:
        name: zabbix
        password: zabbix-password
        host: '*'
        priv: '*.*:ALL'
        state: present


    - name: enable httpd network connect
      command: setsebool -P httpd_can_network_connect=1

    - name: Extract foo.tgz into /var/lib/foo
      command: 'gunzip /usr/share/doc/zabbix-server-mysql-4.0.22/create.sql.gz'


    - name: Import create.sql to mysql
      mysql_db:
        state: import
        name: zabbix
        target: /usr/share/doc/zabbix-server-mysql-4.0.22/create.sql





  handlers:
    - name: Restart httpd
      listen: "restart httpd"
      service:
        name: httpd
        state: restarted
    - name: Restart firewalld
      listen: "restart firewalld"
      service:
        name: firewalld
        state: restarted
